<?php

namespace APIBundle\Repository;

/**
 * CountersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountersRepository extends \Doctrine\ORM\EntityRepository
{
}
